version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-olva-courier
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: olva_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - olva-network

volumes:
  mysql-data:

networks:
  olva-network:
    driver: bridge
